MediteranExpress/urls.py
# MediteranExpress/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('garage/', views.garage, name='garage'),
    path('warehouse-new/', views.warehouse_new, name='warehouse_new'),
    path('autopark/', views.autopark, name='autopark'),
    path('add-item/', views.add_item, name='add_item'),
    path('add-item-form/', views.add_item_form, name='add_item_form'),
    path('edit-item/<int:item_id>/', views.edit_item, name='warehouse_item_edit'),
    path('warehouse/delete/<int:item_id>/', views.delete_item, name='delete_item'),
    path('autopark/add_car/', views.add_car, name='add_car'),
    path('autopark/edit_car/<str:vin_code>/', views.edit_car, name='edit_car'),
    path('autopark/car/<str:vin_code>/', views.car_detail, name='car_detail'),
    path('autopark/save_work_or_add/<str:vin_code>/', views.save_work_or_add, name='save_work_or_add'),
    path('autopark/add_fault/<str:vin_code>/', views.add_fault, name='add_fault'),
    path('autopark/work_detail/<int:work_id>/', views.work_detail, name='work_detail'),
    path('autopark/fault_detail/<int:fault_id>/', views.fault_detail, name='fault_detail'),
    path('warehouse/search_part/', views.search_part, name='search_part'),
    path('mechanics/', views.mechanics_list, name='mechanics_list'),
    path('add_mechanic/', views.add_mechanic, name='add_mechanic'),
    path('mechanic/<int:pk>/', views.mechanic_detail, name='mechanic_detail'),
    path('mechanic/<int:pk>/add_mechanic_work/', views.add_mechanic_work, name='add_mechanic_work'),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('register/', views.register_user, name='register_user'),
    path('autopark_main/', views.autopark_main, name='autopark_main'),
    path('drivers/', views.drivers, name='drivers'),
    path('parts-list/', views.parts_list, name='parts_list'),
    path('update_car_status/', views.update_car_status, name='update_car_status'),



]

main/models.py
from django.db import models
from django.utils import timezone


class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Car(models.Model):
    STATUS_CHOICES = [
        ('Исправен на линии', 'Исправен на линии'),
        ('Неисправен на линии', 'Неисправен на линии'),
        ('В ремонте', 'В ремонте'),
        ('Утиль', 'Утиль'),
    ]
    brand = models.CharField(max_length=100)  # Марка автомобиля
    model = models.CharField(max_length=100)  # Модель автомобиля
    vin_code = models.CharField(max_length=17, unique=True, primary_key=True)  # Вин-код
    engine_number = models.CharField(max_length=100)  # Номер двигателя
    engine_volume = models.DecimalField(max_digits=5, decimal_places=2)  # Объем двигателя
    year_of_manufacture = models.IntegerField()  # Год выпуска
    mileage = models.IntegerField(default=0)  # Пробег
    gearbox_type = models.CharField(max_length=50)  # Вид КПП
    state_number = models.CharField(max_length=20)  # Госномер
    status = models.CharField(max_length=50)  # Статус


    def __str__(self):
        return f"{self.brand} {self.model} ({self.vin_code})"

class WorkPerformed(models.Model):
    vin_code = models.ForeignKey(Car, on_delete=models.CASCADE)
    mileage = models.IntegerField()
    work_name = models.CharField(max_length=255)
    used_parts = models.CharField(max_length=255)
    quantity = models.IntegerField()
    article = models.CharField(max_length=255)
    part_manufacturer = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    executor = models.CharField(max_length=255, null=True, blank=True)

    from django.db import models

class Work(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    date = models.DateField()
    mileage = models.IntegerField()
    work_name = models.TextField()
    article = models.CharField(max_length=100, blank=True, null=True)
    part_name = models.CharField(max_length=100, blank=True, null=True)
    part_manufacturer = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.date} - {self.work_name} ({self.vin_code})"

class Recommendation(models.Model):
    date = models.DateField()  # Дата
    vin_code = models.ForeignKey(Car, on_delete=models.CASCADE)  # Вин-код
    recommendation = models.TextField()  # Рекомендации

    def __str__(self):
        return f"{self.date} - {self.recommendation}"

class DriverComplaint(models.Model):
    date = models.DateField()  # Дата
    vin_code = models.ForeignKey(Car, on_delete=models.CASCADE)  # Вин-код
    complaint_text = models.TextField()  # Текст жалобы

    def __str__(self):
        return f"{self.date} - {self.complaint_text}"

class Fault(models.Model):
    vin_code = models.ForeignKey(Car, on_delete=models.CASCADE)  # Вин-код
    description = models.CharField(max_length=255)  # Неисправность
    date = models.DateField(auto_now_add=True)  # Дата
    criticality = models.CharField(max_length=50)  # Критичность
    mileage = models.IntegerField()  # Пробег

    def __str__(self):
        return f"{self.date} - {self.description} ({self.criticality})"

class Model(models.Model):
    name = models.CharField(max_length=100, unique=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class EngineParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class TransmissionParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class PneumaticParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class ChassisParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class BrakeParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class SteeringParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class ElectricityParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class ClimateParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class CarBodyParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class InteriorParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class MaintenanceParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class LiquidsParts(models.Model):
    availability = models.BooleanField(default=True)
    article = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Item(models.Model):
    availability = models.CharField(max_length=10, default='green', blank=True)
    article = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    size = models.CharField(max_length=100, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=0)
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    part_type = models.CharField(max_length=100)

    # Внешний ключ на соответствующую категорию
    engine_part = models.ForeignKey(EngineParts, on_delete=models.CASCADE, null=True, blank=True)
    transmission_part = models.ForeignKey(TransmissionParts, on_delete=models.CASCADE, null=True, blank=True)
    pneumatic_part = models.ForeignKey(PneumaticParts, on_delete=models.CASCADE, null=True, blank=True)
    chassis_parts = models.ForeignKey(ChassisParts, on_delete=models.CASCADE, null=True, blank=True)

main/forms.py
# main/forms.py

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from .models import Car, WorkPerformed, Fault, Brand, Model, Item, Mechanic
from django.db import transaction

class CarForm(forms.ModelForm):
    STATUS_CHOICES = [
        ('Исправен на линии', 'Исправен на линии'),
        ('Неисправен на линии', 'Неисправен на линии'),
        ('В ремонте', 'В ремонте'),
        ('Утиль', 'Утиль'),
    ]

    vin_code = forms.CharField(
        widget=forms.TextInput(attrs={
            'oninput': 'this.value = this.value.toUpperCase()'
        })
    )
    status = forms.ChoiceField(choices=STATUS_CHOICES)

    class Meta:
        model = Car
        fields = [
            'brand', 'model', 'vin_code', 'engine_number',
            'engine_volume', 'year_of_manufacture', 'mileage',
            'gearbox_type', 'state_number', 'status'
        ]

    def clean_year_of_manufacture(self):
        year = self.cleaned_data['year_of_manufacture']
        if year < 1886 or year > 2024:
            raise ValidationError('Недопустимый год выпуска.')
        return year

    def clean_mileage(self):
        mileage = self.cleaned_data['mileage']
        if mileage < 0:
            raise ValidationError('Пробег не может быть отрицательным.')
        return mileage

class WorkForm(forms.ModelForm):
    date = forms.DateTimeField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = WorkPerformed
        fields = ['date', 'mileage', 'work_name', 'used_parts', 'quantity', 'article', 'part_manufacturer']

    def __init__(self, *args, **kwargs):
        self.car = kwargs.pop('car', None)
        super(WorkForm, self).__init__(*args, **kwargs)

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if quantity <= 0:
            raise ValidationError('Количество должно быть положительным.')
        return quantity

    def clean_mileage(self):
        mileage = self.cleaned_data['mileage']
        if self.car and mileage < self.car.mileage:
            raise ValidationError('Пробег не может быть меньше текущего пробега автомобиля.')
        return mileage

    @transaction.atomic
    def save(self, commit=True):
        instance = super(WorkForm, self).save(commit=False)

        # Снижение количества запчастей на складе, если запчасть найдена
        part_article = self.cleaned_data.get('article')
        if part_article:
            try:
                part = Item.objects.get(article=part_article)
                if part.quantity > 0:
                    part.quantity -= 1
                    part.save()
                else:
                    # Запчасть есть в базе, но недостаточное количество
                    raise ValidationError('Недостаточное количество запчастей на складе.')
            except Item.DoesNotExist:
                # Если запчасть не найдена, продолжить без ошибок
                pass  # Запчасть отсутствует на складе, но мы продолжаем сохранение

        if commit:
            instance.save()
        return instance

class FaultForm(forms.ModelForm):
    CRITICALITY_CHOICES = [
        ('Низкая', 'Низкая'),
        ('Средняя', 'Средняя'),
        ('Высокая', 'Высокая'),
    ]

    criticality = forms.ChoiceField(choices=CRITICALITY_CHOICES)

    class Meta:
        model = Fault
        fields = ['description', 'criticality', 'mileage']

    def __init__(self, *args, **kwargs):
        self.car = kwargs.pop('car', None)
        super(FaultForm, self).__init__(*args, **kwargs)

    def clean_mileage(self):
        mileage = self.cleaned_data['mileage']
        if self.car and mileage < self.car.mileage:
            raise ValidationError('Пробег не может быть меньше текущего пробега автомобиля.')
        if mileage < 0:
            raise ValidationError('Пробег не может быть отрицательным.')
        return mileage

    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) < 5 or len(description) > 50:
            raise ValidationError('Описание неисправности должно содержать от 5 до 50 символов.')
        return description

class ItemForm(forms.ModelForm):
    brand = forms.ModelChoiceField(queryset=Brand.objects.all(), label='Бренд')
    model = forms.ModelChoiceField(queryset=Model.objects.all(), label='Модель')

    class Meta:
        model = Item
        fields = ['article', 'name', 'size', 'quantity', 'brand', 'model', 'manufacturer', 'part_type']








class MechanicForm(forms.ModelForm):
    class Meta:
        model = Mechanic
        fields = ['first_name', 'last_name']

class RegisterUserForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, label='Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Повторите пароль')
    group = forms.ChoiceField(choices=[
        ('Водители', 'Водители'),
        ('Механики', 'Механики'),
        ('Администраторы', 'Администраторы')
    ], label='Группа')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'password1', 'password2', 'group']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('Пароли не совпадают.')
        return password2

    def clean_group(self):
        group = self.cleaned_data.get('group')
        if not group:
            raise ValidationError('Необходимо выбрать группу.')
        return group

main/templates/main/add_mechanic.html
{% block content %}
<h2>Добавить Механика</h2>
    <style>
    /* Оформление всплывающего окна */
    .popup {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        z-index: 10;
        width: 400px;
        max-width: 90%;
        max-height: 90%;
        overflow-y: auto;
    }

    /* Стили для заголовка */
    h2 {
        margin-top: 0;
        font-family: Arial, sans-serif;
        font-size: 20px;
        color: #333;
        text-align: center;
    }

    /* Стили для формы */
    form {
        display: flex;
        flex-direction: column;
        gap: 15px;
    }

    label {
        font-family: Arial, sans-serif;
        font-size: 14px;
        color: #555;
    }

    input[type="text"] {
        width: calc(100% - 10px);
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 14px;
    }

    /* Стили для кнопок */
    .close-button {
        position: absolute;
        top: 10px;
        right: 10px;
        font-size: 18px;
        background: none;
        border: none;
        color: #666;
        cursor: pointer;
    }

    .close-button:hover {
        color: #ff4d4d;
    }

    button[type="submit"] {
        align-self: center;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        transition: background-color 0.3s;
    }

    button[type="submit"]:hover {
        background-color: #0056b3;
    }
</style>

<form id="mechanicForm" method="post" action="{% url 'add_mechanic' %}">
    {% csrf_token %}
    <div>
        <label for="first_name">Имя:</label>
        <input type="text" id="first_name" name="first_name" required>
    </div>
    <div>
        <label for="last_name">Фамилия:</label>
        <input type="text" id="last_name" name="last_name" required>
    </div>
    <button type="submit">Сохранить</button>
</form>

<script>
    document.getElementById('mechanicForm').addEventListener('submit', function(event) {
        event.preventDefault();
        const form = this;

        // Отправка данных формы через AJAX для сохранения механика
        fetch(form.action, {
            method: 'POST',
            body: new FormData(form),
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
                'X-CSRFToken': form.querySelector('[name=csrfmiddlewaretoken]').value
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                window.parent.location.reload();
                window.parent.closePopup();
            } else {
                alert('Ошибка при добавлении механика.');
            }
        })
        .catch(error => {
            console.error('Ошибка:', error);
            alert('Произошла ошибка при отправке данных.');
        });
    });
</script>
{% endblock %}

main/templates/main/autopark.html
<!DOCTYPE html>
{% extends 'main/base.html' %}
{% block content %}
     <a href="{% url 'autopark_main' %}" class="back-button">Назад</a>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>Список автобусов</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        .add-car-button {
            display: block;
            margin: 20px auto;
            padding: 10px 20px;
            font-size: 18px;
            text-align: center;
            text-decoration: none;
            color: white;
            background-color: #007bff;
            border-radius: 5px;
            width: 200px;
        }
        .car-item {
            margin: 10px 0;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f8f9fa;
            text-decoration: none;
            color: #000;
            display: block;
        }
        .car-item:hover {
            background-color: #e2e6ea;
        }


        .back-button {
        display: inline-block;
        padding: 8px 12px;
        margin: 10px 0;
        font-size: 14px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        cursor: pointer;
        transition: background-color 0.3s, box-shadow 0.3s;
    }

        .back-button:hover {
        background-color: #0056b3;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        text-decoration: none;
    }
    </style>
</head>
<body>
    <div class="container">
        <h1>Список автобусов</h1>
        {% if user.is_authenticated %}
    {% if user.is_staff or user.is_superuser %}

        <a href="{% url 'add_car' %}" class="add-car-button">Добавить автомобиль</a>
    {% else %}
     <p class="no-access-message"></p>
    {% endif %}
{% endif %}
        <div>
            {% for car in cars %}
                <a href="{% url 'car_detail' car.vin_code %}" class="car-item">
                    {{ car.brand }} {{ car.model }} - {{ car.state_number }}
                </a>
            {% empty %}
                <p>Нет автомобилей в автопарке.</p>
            {% endfor %}
        </div>
        <a href="{% url 'home' %}">Назад на главную</a>
    </div>
</body>
</html>
{% endblock %}

main/templates/main/autopark_main.html
{% extends 'main/base.html' %}

{% block title %}Автопарк - MediteranExpress{% endblock %}

{% block content %}
         <a href="{% url 'home' %}" class="back-button">Назад</a>
<div class="main-content">
    {% if user.is_authenticated %}
        <a href="{% url 'autopark' %}" class="box">Список автобусов</a>
        <a href="{% url 'drivers' %}" class="box">Водители</a>
    {% else %}
        <p>Для доступа к системе необходимо авторизоваться.</p>
        <script>
            window.onload = function() {
                document.getElementById('loginModal').style.display = 'block';
            }
        </script>
    {% endif %}
</div>

<div id="loginModal" class="modal">
    <div class="modal-content">
        <h2>Авторизация</h2>
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <div>
                <label for="username">Имя пользователя:</label>
                <input type="text" name="username" id="username" required>
            </div>
            <div>
                <label for="password">Пароль:</label>
                <input type="password" name="password" id="password" required>
            </div>
            <button type="submit">Войти</button>
        </form>
    </div>
</div>

<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 30%;
        position: relative;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    .main-content {
        text-align: center;
        margin-top: 50px;
    }

    .box {
        display: inline-block;
        margin: 20px;
        padding: 20px;
        background-color: #f0f0f0;
        color: #333;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s, color 0.3s;
    }

    .box:hover {
        background-color: #007bff;
        color: white;
    }

            .back-button {
        display: inline-block;
        padding: 8px 12px;
        margin: 10px 0;
        font-size: 14px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        cursor: pointer;
        transition: background-color 0.3s, box-shadow 0.3s;
    }

        .back-button:hover {
        background-color: #0056b3;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        text-decoration: none;
    }
</style>
{% endblock %}

main/templates/main/base.html
<!-- main/templates/main/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MediteranExpress{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .header {
            background-color: #fff;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .user-info {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .username {
            font-weight: bold;
        }
        .sign-out, .sign-in {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 5px 15px;
            border-radius: 5px;
            cursor: pointer;
        }
        .sign-out:hover, .sign-in:hover {
            background-color: #0056b3;
        }
        .header .title {
            font-size: 24px;
            color: #0056b3;
            font-weight: bold;
            font-style: italic;
        }
        .header .home-link {
            text-decoration: none;
            color: #333;
            font-size: 18px;
        }
        .main-content {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 80vh;
        }
        .main-content .box {
            width: 45%;
            height: 45%;
            margin: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-decoration: none;
            color: #333;
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <a href="{% url 'home' %}" class="home-link">🏠</a>
        <div class="title">MediteranExpress</div>
        {% if user.is_authenticated %}
        <div class="user-info">
            <span class="username">{{ user.username }}</span>
            <a href="{% url 'login' %}">
                <button class="sign-out">Выйти</button>
            </a>
        </div>
        {% else %}
        <a href="{% url 'login' %}">
            <button class="sign-in">Sign in</button>
        </a>
        {% endif %}
    </div>
    {% block content %}{% endblock %}
</body>
</html>

main/templates/main/edit_car.html
<!DOCTYPE html>
<html>
<head>
    <title>Редактировать автомобиль</title>
    <script>
        function toUpperCaseInput(event) {
            event.target.value = event.target.value.toUpperCase();
        }
    </script>
</head>
<body>
    <h1>Редактировать автомобиль {{ car.brand }} {{ car.model }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
         <input type="text" name="vin_code" id="id_vin_code" value="{{ form.vin_code.value }}" oninput="toUpperCaseInput(event)">
        <button type="submit">Сохранить</button>
    </form>
    <a href="{% url 'car_detail' car.vin_code %}">Назад к карточке автомобиля</a>
</body>
</html>

main/templates/main/edit_item.html
<!-- main/templates/main/edit_item.html -->

{% extends 'main/base.html' %}

{% block title %}Редактировать элемент{% endblock %}

{% block content %}
<h1>Редактировать элемент</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

main/templates/main/fault_detail.html
<div>
    <h2>Детали неисправности</h2>
    <p><strong>Описание:</strong> {{ fault.description }}</p>
    <p><strong>Критичность:</strong> {{ fault.criticality }}</p>
    <p><strong>Пробег:</strong> {{ fault.mileage }} км</p>
</div>

main/templates/main/work_detail.html
<div>
    <h2>Детали работы</h2>
    <p><strong>Дата:</strong> {{ work.date }}</p>
    <p><strong>Пробег:</strong> {{ work.mileage }} км</p>
    <p><strong>Работы:</strong> {{ work.work_name }}</p>
    <p><strong>Использованные запчасти:</strong> {{ work.used_parts }}</p>
    <p><strong>Количество:</strong> {{ work.quantity }}</p>
    <p><strong>Артикул:</strong> {{ work.article }}</p>
</div>